### ISSUE TITLE
host field in kernel.json not parsed

### ISSUE THREAD

**Issue by leezu** [danielballan/remotekernel#3]
Unfortunately remotekernel fails (for me) to read the host field provided in a kernel.json field.

Considering the following kernel.json
```
{
  "argv":["python3", "-m", "IPython.kernel", "-f", "{connection_file}"],
  "display_name":"Python 3 on dycpu2",
  "host":"dycpu2"
}
```

Starting a jupyter notebook with that kernel will fail as follows:

```
[E 20:06:07.500 NotebookApp] Unhandled error in API request                                                                                                       [40/410]
    Traceback (most recent call last):
      File "/home/leonard/.local/lib/python3.5/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/leonard/.local/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/leonard/.local/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/leonard/.local/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/leonard/.local/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/home/leonard/.local/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/leonard/.local/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/leonard/.local/lib/python3.5/site-packages/remotekernel/manager.py", line 62, in start_kernel
        self.ip = socket.gethostbyname(self.kernel_spec.host)
    AttributeError: 'KernelSpec' object has no attribute 'host'

[E 20:06:07.573 NotebookApp] {
      "X-Requested-With": "XMLHttpRequest",
      "Dnt": "1",
      "Referer": "http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python3dycpu2",
      "Cookie": "_xsrf=2|4234a35f|22c51cac3f582564aac885d827a498d4|1486970355; username-localhost-8888=\"2|1:0|10:1486987547|23:username-localhost-8888|44:NzU2NWU1YTk3ZDd
lNDc4MDlhNGZiOWM5ZTIzOTZlNjQ=|45f935b57385625994102302413615a200c020120c8daf355598329dddc5a934\"",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.5",
      "X-Xsrftoken": "2|4234a35f|22c51cac3f582564aac885d827a498d4|1486970355",
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0",
      "Content-Length": "98",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Connection": "keep-alive",
      "Content-Type": "application/json"
    }

[E 20:06:07.573 NotebookApp] 500 POST /api/sessions (127.0.0.1) 91.26ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python3dycpu2
```

Indeed by printing the KernelSpec object it can be seen that the host attribute was not added:

```
{'_cross_validation_lock': False,
 '_trait_notifiers': {},
 '_trait_validators': {},
 '_trait_values': {'argv': ['python3',
                            '-m',
                            'IPython.kernel',
                            '-f',
                            '{connection_file}'],
                   'display_name': 'Python 3 on dycpu2',
                   'language': '',
                   'resource_dir': '/home/leonard/.local/share/jupyter/kernels/python3dycpu2'}}
```

I am not sure why this is happening and would be happy if you could point me to any mistake I made causing this error.

**Comment by danielballan** [comment]
Hi @leezu. Sorry for the long delay, I just noticed this. If you customize the `kernel_manager_class` as documented at the bottom of the README, you should have a custom KernelSpec that [adds a host field](https://github.com/danielballan/remotekernel/blob/master/remotekernel/kernelspec.py#L5).

**Comment by leezu** [comment]
Hey @danielballan, no worries regarding the delay. However I am not quite sure how to understand your comment.
```
➜  ~ jupyter kernelspec list
Available kernels:
  python2_dycpu1    /home/leonard/.local/share/jupyter/kernels/python2_dycpu1
  python2_dycpu2    /home/leonard/.local/share/jupyter/kernels/python2_dycpu2
  python3           /home/leonard/.local/share/jupyter/kernels/python3
  python3_dycpu1    /home/leonard/.local/share/jupyter/kernels/python3_dycpu1
  python3_dycpu2    /home/leonard/.local/share/jupyter/kernels/python3_dycpu2
```

Where each of the pythonX_dycpuY directories contains a kernel.json with entries like:

```
{
  "argv":["python3", "-m", "IPython.kernel", "-f", "{connection_file}"],
  "display_name":"Python 2 on dycpu2",
  "host":"dycpu2"
}
```

Is that what you mean with having a custom KernelSpec? If not, I assume you are referring to adapting kernelspec.py but unfortunately I'm not sure how I could apply such a customized KernelSpec.

**Comment by danielballan** [comment]
Your kernel.json is looks right. Yes, I'm talking about, effectively, adapting kernelspec.py. Fortunately IPython/Jupyter gives you an easy way to do this (no need to edit the file). See the bottom of the [README](https://github.com/danielballan/remotekernel#run). Did you try that?

**Comment by danielballan** [comment]
I'm going to close this issue, but please reopen if I can provide more help!
